### ISSUE TITLE
Tabbar autohide doesn't work

### ISSUE THREAD

**Issue by CavaleriOmar** [dexeonify/firefox-css#1]
Firefox 95.0.2 on ArchLinux

I followed the instructions (it's not the first userchrome I use), but the tabbar autohide doesn't work... as you can see from my attached screenshot
![Screenshot_20220108_113256](https://user-images.githubusercontent.com/54171779/148641105-9fff3a18-9981-4a26-b29c-bc536c7f2ab7.png)

**Comment by dexeonify** [comment]
Hmm, I'm not sure if there's anything else to set up. Are you sure you have set the "preface value" in Sidebery settings?
These is [some instructions for Sidebery](https://github.com/dexeonify/firefox-css#vertical-tabs) btw, not just `userChrome.css`.

**Comment by dexeonify** [comment]
Works fine on my Arch:tm: VM.
![sidebery_linux](https://user-images.githubusercontent.com/72267349/148646341-a81375c0-5346-4c9c-8ccb-3e23d88ca387.png)

Though I think there's going to be issues with the windows control, at least with mine it didn't properly moved to the left, so I kept KDE default titlebar.

**Comment by Mojavve** [comment]
Mine will autohide but first I have to toggle sidebery off and on again when first opening Firefox.  Not a huge deal though, I just have the toggle bound to my F1 key.

**Comment by dexeonify** [comment]
Yep, I've noticed the same thing after a fresh restart, presumably because Sidebery hasn't set the window preface value.
